// <auto-generated />
using Hackaton2024.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackaton2024.API.Migrations
{
    [DbContext(typeof(HackatonDbContext))]
    [Migration("20241201032226_added-picture-urls")]
    partial class addedpictureurls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hackaton2024.API.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bieganie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Czytanie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gotowanie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kolarstwo",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pływanie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Malowanie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hiking",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Taniec",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ogrodnictwo",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pisanie",
                            PictureUrl = "https://images-ext-1.discordapp.net/external/NP7oXacXlpjTkM0U1j-qvy8ze8uiLKF1mznDUH7DjCU/https/bi.im-g.pl/im/47/a9/19/z26908487AMP%2CPol-godziny-jazdy-na-rowerze-tygodniowo-zapewnia-o.jpg?format=webp&width=994&height=663",
                            Stage = 0
                        });
                });

            modelBuilder.Entity("Hackaton2024.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hackaton2024.API.Entities.UserActivity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("Hackaton2024.API.Entities.UserActivity", b =>
                {
                    b.HasOne("Hackaton2024.API.Entities.Activity", "Activity")
                        .WithMany("UserActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackaton2024.API.Entities.User", "User")
                        .WithMany("UserActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hackaton2024.API.Entities.Activity", b =>
                {
                    b.Navigation("UserActivities");
                });

            modelBuilder.Entity("Hackaton2024.API.Entities.User", b =>
                {
                    b.Navigation("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
